#!/usr/bin/bash

#COLORS

RED='\e[31m'
GREEN='\e[32m'
BLUE='\e[34m'
BLACK='\e[33m'
PURPLE='\e[35m'
CYAN='\e[36m'
YELLOW='\e[1;33m'
BOLD='\033[1m' #That not works on all terminals
ENDCOLOR="\e[0m" # Resets color and more to default not always necessary but good a practice

#Lets add some attributes to know what exactly people run this code using

OS="$(uname -o)" #For operating system
CPU="$(uname -m)" #For Cpu architecture like ARM, X86, X86-64 etc                                                                    Kernel="$(uname -sr)" #For kernel
UPTIME="$(uptime -p)"
USER="$(whoami)"
de="$(hostname)" #short for 'device name'
ip="$(curl -s ifconfig.me)"
# SHELL is literally $SHELL so we dont need re write it

memory_info=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

# -e used in echo function because that lets print fancy text with colors and more

echo -e "${CYAN}${BOLD}${de}@${USER}${ENDCOLOR}"
echo -e "${PURPLE}${BOLD}Shell: $SHELL${ENDCOLOR}"
echo -e "${YELLOW}${BOLD}OS: $OS ${ENDCOLOR}"
echo -e "${RED}${BOLD}Kernel: $Kernel${ENDCOLOR}"
echo -e "${BLUE}${BOLD}CPU architecture: $CPU ${ENDCOLOR}"
echo -e "${GREEN}${BOLD}Uptime: $UPTIME ${ENDCOLOR}"
echo -e "${PURPLE}${BOLD}RAM $memory_info ${ENDCOLOR}"
echo -e "${CYAN}${BOLD}Ip: $ip ${ENDCOLOR}"
